DROP TABLE IF EXISTS RESTAURANT_INFO;
DROP TABLE IF EXISTS MENU;
DROP TABLE IF EXISTS BOOKER;
DROP TABLE IF EXISTS RESERVATION_MENU;
DROP TABLE IF EXISTS RESERVATION;

CREATE TABLE RESTAURANT_INFO (RestaurantName VARCHAR(20) PRIMARY KEY NOT NULL,
	Location VARCHAR(100),
	PhoneNumber INT,
    InrtoDuction VARCHAR(100),
    Notice VARCHAR(100),
    CancellationPolicy TEXT(100));

CREATE TABLE MENU (MenuNo INT PRIMARY KEY NOT NULL,
	MenuName VARCHAR(14) NOT NULL,
	ManuPrice INT NOT NULL,
    MenuImage MEDIUMBLOB NOT NULL,
    MenuIngredient VARCHAR(100) NOT NULL);

CREATE TABLE BOOKER (BookerNo INT PRIMARY KEY NOT NULL,
	BookerName VARCHAR(14) NOT NULL,
    BookerPhone INT NOT NULL,
    BookerPaymentInfo VARCHAR(100) NOT NULL,
    BookerPeopleNum INT NOT NULL,
    Significant VARCHAR(50));

INSERT INTO BOOKER VALUES (1, 'KIM', '01012341234', 'N', 3, '');
INSERT INTO BOOKER VALUES (2, 'PARK', '01043214321', 'N', 3, '');

CREATE TABLE RESERVATION (ResNo INT PRIMARY KEY NOT NULL,
    ResTime TIME NOT NULL,
	ResSeat INT NOT NULL);

INSERT INTO RESERVATION VALUES (1, '12:00:00', 1);
INSERT INTO RESERVATION VALUES (2, '12:00:00', 2);

CREATE TABLE RESERVATION_MENU (ResMenuno INT PRIMARY KEY NOT NULL,
	ResNo INT NOT NULL,
    MenuNo INT NOT NULL,
    CONSTRAINT FK_RESNO FOREIGN KEY RESERVATION_MENU(ResNo) REFERENCES RESERVATION(ResNo));

INSERT INTO RESERVATION_MENU VALUES (1, 1, 1);
INSERT INTO RESERVATION_MENU VALUES (2, 1, 2);
INSERT INTO RESERVATION_MENU VALUES (3, 1, 3);
INSERT INTO RESERVATION_MENU VALUES (4, 2, 1);
INSERT INTO RESERVATION_MENU VALUES (5, 2, 2);

SELECT R.RESNO, B.BOOKERNO, B.BOOKERNAME, M.MENUNO, R.RESTIME, R.RESSEAT
FROM RESERVATION R
LEFT JOIN BOOKER B 
ON B.BookerNo=R.ResNo 
LEFT JOIN RESERVATION_MENU M 
ON M.ResNo=R.ResNo;